### ISSUE TITLE
VTK 8.1.0 using Python 3.5.2 

### ISSUE THREAD

**Issue by defineconst** [mvanmoer/eclipsegrdecl2vtk#2]
![image](https://user-images.githubusercontent.com/3112684/74300170-f5ec8c00-4d89-11ea-8573-48f35dfcab6d.png)
D:\ProgramData\Anaconda3\envs\pyGRDECL\python.exe E:/3000_3D_2020/eclipsegrdecl2vtk-master/eclipse2vtk.py
else section:  /

Traceback (most recent call last):
  File "E:/3000_3D_2020/eclipsegrdecl2vtk-master/eclipse2vtk.py", line 219, in <module>
    ugrid = ConvertGrid(testfile)
  File "E:/3000_3D_2020/eclipsegrdecl2vtk-master/eclipse2vtk.py", line 64, in ConvertGrid
    xcoords = coords[0::3]
TypeError: 'map' object is not subscriptable

Process finished with exit code 1

**Comment by mvanmoer** [comment]
Please give the result of running vtkpython --version from the command line.

**Comment by mvanmoer** [comment]
@defineconst -- What does D:\ProgramData\Anaconda3\envs\pyGRDECL\python.exe -V return?

The TypeError is because ConvertGrid(testfile) calls ReadSection(gridfile) on line 61. ReadSection() calls the map() function on line 187. This map() is what was causing the problem. In Python 2, map() was a function that returned a list. In Python 3, map() returns an iterable. The fix was to wrap that map() call inside of a list() call.

Please make sure that the code change on line 187 was merged into your repo and please verify that Anaconda is indeed calling Python 3.
